language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

install:
  - "pip install -r requirements.txt"

script:
  - pytest .travis/tests.py

addons:
  srcclr: true