language: python

matrix :
  include:
  - python: '2.6'
  - python: '2.7'
    addons:
      srcclr: true
  - python: '3.5'
  - python: '3.5-dev'
  - python: '3.6-dev'
  - python: 'nightly'

install:
  - "pip install -r requirements.txt"

# TODO change .travis/test to setup.py test

script:
  - pytest .travis/tests.py
  - coverage run .travis/tests.py

after_success:
  coveralls
