version: "3"

services:
  db:
    build: ./db
    volumes:
      - /mnt/sdc:/mnt/sdc
    ports:
      - 5432:5432
  mqtt:
    build: ./mqtt
    ports:
      - 15672:15672
  fetch:
    build: ./fetch
    links:
      - mqtt
    depends_on:
      - mqtt
    env_file: _deployment/fetch.env
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints: [node.role == worker, engine.labels.db == true]
  parser:
    build: ./parser
    links:
      - mqtt
    depends_on:
      - mqtt
  store:
    build: ./store
    links:
      - mqtt
      - db
    depends_on:
      - mqtt
      - db
  filter:
    build: ./filter
    links:
      - mqtt
      - db
    depends_on:
      - mqtt
      - db
  search_backend:
    build: ./search_backend
    env_file: _deployment/fetch.env
    links:
      - mqtt
      - db
    depends_on:
      - mqtt
      - db
    ports:
      - 80:80



