version: "2"

services:
  db:
    build: ./db
    volumes:
      - /mnt/sdc:/mnt/sdc
    ports:
      - 5432:5432
  mqtt:
    build: ./mqtt
    ports:
      - 15672:15672
  fetch:
    build: ./fetch
    links:
      - mqtt
    depends_on:
      - mqtt
    env_file: _deployment/fetch.env
  fetch2:
    build: ./fetch
    links:
      - mqtt
    depends_on:
      - mqtt
    env_file: _deployment/fetch.env
  fetch3:
    build: ./fetch
    links:
      - mqtt
    depends_on:
      - mqtt
    env_file: _deployment/fetch.env
  fetch4:
    build: ./fetch
    links:
      - mqtt
    depends_on:
      - mqtt
    env_file: _deployment/fetch.env
  parser:
    build: ./parser
    links:
      - mqtt
    depends_on:
      - mqtt
  store:
    build: ./store
    links:
      - mqtt
      - db
    depends_on:
      - mqtt
      - db
  filter:
    build: ./filter
    links:
      - mqtt
      - db
    depends_on:
      - mqtt
      - db



